# Generated by Django 5.2.17 on 2026-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(unique=True)),
                ('report_id', models.CharField(max_length=60, unique=True)),
                ('saved_by', models.CharField(default='admin', max_length=100)),
                ('is_locked', models.BooleanField(default=True)),
                ('report_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-report_date', '-id'],
            },
        ),
    ]
